# This workflow will install dependencies, build flask-pyctuator and run mypy and pylint

name: build

on:
  push:
  pull_request:

jobs:
  run_image:
    runs-on: [ubuntu-18.04]
    container:
      image: matanrubin/python-poetry:3.7

    steps:
      - uses: actions/checkout@v2
      - run: make bootstrap
      - run: poetry build -vvv

      - run: poetry install
      - run: make check
